### ISSUE TITLE
Losing Hunger breaking torches

### ISSUE THREAD

**Issue by Noaaan** [mactso/HarderBranchMining#4]
Hello!
This mod looks great! However, i have found a major flaw.
If you are far below the ground, breaking some types of blocks such as torches, will INSTANTLY remove your hunger. By quickly placing torches and breaking them, you almost instantly lose all your hunger. You also instantly lose all of your saturation when breaking a block at around y=11.

The hunger removal seems too agressive. There should be a blacklist for breaking blocks like cobwebs, torches, etc. Hopefully you can get around to fixing this. The mod pairs very well with food-based mods.

**Comment by mactso** [comment]
Thank you for your feedback!

You didn't mention if you were in 1.12.2.  This fixes and work arounds should work in 1.12.2 as well tho the syntax is a little different and you can edit the configuration directly on the Forge Config file instead of editing the "Saves/Server-Config/hbm.toml" file.

This can be fixed in a couple different ways in the configuration file.

### **Fixes and Work arounds**
1) Workaround: Use a tool to break the torch.  It has much lower exhaustion than your empty hand.
If you break torches with a diamond pickaxe, then extra exhaustion is below "1.0" even at bedrock.
_I've confirmed this works tonight._

2) **Fix:** Adjust the **default value** to a lower value.  It's "hbm:default:0" and starts with exhaustion "10.0".   It applies when you break something with an empty hand or undefined tool.  I suggest you change it to 2.0. 

**Example:** hbm:default,0,48,**2.0;**
_I've confirmed this works tonight._
Make sure you change the value in section "Tool Values 6464."  The normal Tool Values section won't work until issue 6464 is fixed with Forge.  Example at the bottom.

3) **Fix:** Add a value "minecraft:torch:0" with custom exhaustion such as "1" to make breaking things with a torch less exhausting.  

_I've confirmed this works tonight._
**Example:** **\rminecraft:torch,0,48,1.0;\n**

If you are in 1.15.2, Make sure you change the HBM.TOML file value in section "Tool Values 6464."  The normal Tool Values section won't work until issue 6464 is fixed with Forge.  Example at the bottom.

Please give me feedback of your opinion on those work arounds.


**### Example**
Until Issue 6464 is fixed, **["Tool Values 6464"]** is the section in HBM.toml to change.

["Tool Values 6464"]
	#Tool String 6464
	defaultToolsActual = "hbm:default,0,48,**2.0;**\n
**\rminecraft:torch,0,48,1.0;\n**

---

I'll lower the empty hand/default/undefined tool value some in the next release and add a torch default value.
It can literally be anything you want to set up.  minecraft:stick, minecraft:torch, minecraft:ladder,nastymob:skull, etc.

**Comment by mactso** [comment]
Okay I have fixed this in 1.15.2- any "soft" items (hardness 1 or less) will not cause exhaustion.
I'm shooting for a fix in 1.12.2 by 3/24/2020.

**Comment by mactso** [comment]
This is fixed in all versions.
