### ISSUE TITLE
Config file suggestion

### ISSUE THREAD

**Issue by bmwalter68** [mactso/HarderBranchMining#9]
Hey MacTso, thanks for the mod!  Just what I was looking for!  I do have a suggestion though...

With heavily modified modpacks I'm worried the tool config string length will get out of control when faced with the combination of many tools and many dimensions.  Thinking about things like Tinkers Construct, Tetra, Mekanism, etc. Based on the TOML spec, if it were structured more along the lines of:

```
[tools]

  [minecraft:diamond_pickaxe]

    [minecraft:overworld]
    depth = 48
    exhaustion = 1.0

    [minecraft:the_nether]
    depth = 124
    exhaustion = 1.2;
```

I think this could also make the file easier to maintain than having to rebuild a giant string for new modpacks.

The other possibility from the spec (which would also work for the block whitelist) is:

```
[tools]
values = [
  "minecraft:diamond_pickaxe,minecraft:overworld,48,1.0",
  "minecraft:diamond_pickaxe,minecraft:the_nether,124,1.2",
  ...
]

[whitelist]
blocks = [
  "ore_stone_variants:coal_ore",
  "ore_stone_variants:iron_ore",
  ...
]
```

Which would probably be easier and closer to what you have from the programmatic side.  I'll see if I can knock out a PR.

Thanks again!

- B

**Comment by Winddbourne** [comment]
I'm not sure my mod pack is "big" but it's definitely heavily modified and that string isn't just intimidating, it's a mess. The thing looks like this by default in 1.36.0.8:

["Tool Values 6464"]
	#Tool String 6464
	defaultToolsActual = "hbm:default,hbm:default_dimension,48,10.0;minecraft:torch,minecraft:overworld,48,0.2;minecraft:wooden_pickaxe,minecraft:overworld,48,8.0;minecraft:stone_pickaxe,minecraft:overworld,48,4.0;minecraft:iron_pickaxe,minecraft:overworld,48,2.0;minecraft:golden_pickaxe,minecraft:overworld,48,1.5;minecraft:diamond_pickaxe,minecraft:overworld,48,1.0;minecraft:wooden_shovel,minecraft:overworld,48,8.0;minecraft:stone_shovel,minecraft:overworld,48,4.0;minecraft:iron_shovel,minecraft:overworld,48,2.0;minecraft:golden_shovel,minecraft:overworld,48,1.5;minecraft:diamond_shovel,minecraft:overworld,48,1.0;minecraft:wooden_axe,minecraft:overworld,48,2.0;minecraft:stone_axe,minecraft:overworld,48,1.0;minecraft:iron_axe,minecraft:overworld,48,0.5;minecraft:golden_axe,minecraft:overworld,48,0.3;minecraft:diamond_axe,minecraft:overworld,48,0.25;minecraft:iron_pickaxe,minecraft:the_nether,124,2.2;minecraft:diamond_pickaxe,minecraft:the_nether,124,1.2;"


What is 6464 supposed to mean?
And I think this means it's only supporting vanilla tools in the Overworld right now?
And one pick in the Nether?
Plus a torch for some reason????? Do I even need that? 
I came here looking for a wiki to break it all down. 

I see default_dimension here and if it's what all the dimensions default to I might want to set it to 2,1 or something instead of 48, 10 and then change everything else from overworld to the mining dimension where I want this curve start at Y128 and go down to 1. My pack has different rules for different realms and this rule applies only to the land of stone, not my Skyblock. 

And, of course, I'd be deleting all the data for the nether listed here, and adding in modded picks to the list. That all would be so much easier though in the format suggested here . . . to the point where I might just separate out things that way INSIDE the string and then get rid of the line breaks when I'm done! 

And the ironic thing is that IF I'm looking at this right my changes actually make everything easier for me. I only want this mod to impact one dimension. I've currently actually got seven in the pack if you include the Overworld. Which is why I was hoping to find a wiki that would clarify my assumptions. lol

But I could be wrong. I only see one pick entry for the nether? Does that mean that all the other picks listed in the string default to 48,10? That's what I'm assuming but . . . it also could mean that the mod isn't impacting other picks at all in the nether.  

I can imagine how hard this would be, and how long that string would get if I was setting custom values for each of seven different dimensions with a lot ofdifferent modded picks! 

Speaking of which would this count something like immersive engineering's mining drill as a pick? lol

**Comment by mactso** [comment]
Hi Guys, 
Not sure how I missed this issue.  I appreciate your raising it.

Okay so addressing your questions:
1)  Issue 6464 refers to the forge issue 6464 by Calaboo.  The config system is broken for string arrays.   A fix was written for it and rejected by the forge team.  So instead of having a lovely config screen with one line per pick, I have to use a semi colon deleted file or JSON which is extremely brittle in my experience.   We used the 6464 as a placeholder assuming Forge would accept the fixes for this and that it was a temporary issue.  unfortunately, they rejected it and said forge should no longer maintain a config gui.
 
Bmwalter68 , regarding the TOML suggestions.
For your first suggestion, ( [minecraft:overworld] ), this means the mod must be hard coded to support each dimension.  I.e. there must be a specific bit of code written to recognize [minecraft:overworld].   If someone put in [Abyssal:green], it won't be recognized.   The automatic forge toml processor won't do it.

I'll look into how other mods do it.  

For your second suggestion, it's also broken in Forge after 1.12.2 for string arrays.  This all worked in forge 1.12.2 but it's been broken since they added TOML for strings arrays.  We have many mods now so it may be worth writing a custom Config library now.  Lupicus is trying a couple ideas as I speak/write but they are all crashing.

--- 
Okay so...
2) The values in the file are the default values.  When HBM can't find the specific mod:tool, it falls back to the default value.  If it can't find that it falls back to the Overworld default.  If HBM can't find that, it falls back to internal defaults (which are identical to the values in the default file).

3) as a work around you can replace ";" with ";\n" or ";" and a linefeed and it will become 
"hbm:default,hbm:default_dimension,48,10.0;
minecraft:torch,minecraft:overworld,48,0.2;
minecraft:wooden_pickaxe,minecraft:overworld,48,8.0;
minecraft:stone_pickaxe,minecraft:overworld,48,4.0;
..."
The linefeeds are ignored when it reads the config file.  
Another option is to keep a custom text file with all the tools you want to have configured.


Winddbourne,
If you set up the default with values of "1.0" speed then tools will will behave normally everywhere.  Then you can have a set of lines just for the pickaxes in with the mining dimension.
default
"hbm:default,hbm:default_dimension,48,1.0;
miningdimensionmod:miningdimensionname, minecraft:diamond_pickaxe, 124, (difficulty value like 8.0);
miningdimensionmod:miningdimensionname, amodname:the_mods_pickaxe_id, 124, (difficulty value like 8.0); "
 
4) The nether entry is an example for how to make entries for other modded dimensions.  Yes, the default applies if the tool isn't defined unless the mod has tool that overrides the default forge/minecraft code (many picks that excavate do this).

P.S. we looked at the Tinker's code and it looks like they don't support either specific or unknown modded dimensions.  They have their *own* code in particular dimensions that generates their slime islands but they don't have the capability to recognize new dimensions created by other new mods.

With Best Regards,
Two Guys,
MacTso

(Sorry for the delay!)

With HBM, you can put in a *string* of *any* mod that's written in the future and HBM would work there.  The TOML essentially "hard codes" those dimensions - so you can't handle a mod that isn't written yet.

We are continuing to look if there is a better way to do this that will have a cleaner config file.

**Comment by mactso** [comment]
Please post any follow up questions and I'll do my best to answer them.

I'll consider a custom CSV file (as used in Spawn Biome Utility) when we go to 17 too.

I wish forge had accepted that other guys fix to the config system.

**Comment by mactso** [comment]
Closing this isuee.
